### ISSUE TITLE
Possible Inaccuracy in SRAM emulation

### ISSUE THREAD

**Issue by diabl0w** [Rodrigodd/gameroy#10]
Hi, i've been trying your emulator to run Gen 1 Pokemon glitches. One of the most popular glitches is the ['SRAM Glitch'](https://glitchcity.wiki/wiki/SRAM_glitch). It does not seem to be working on yoir emulator. I tried both the android and desktop linux versions

**Comment by Rodrigodd** [comment]
Your link has the following comment:

> Even if the player does not have an existing save file (e.g. on a fresh cart), it is still recommended to clear the save file anyway. Clearing the save file will set the SRAM to all 0xFF bytes, which guarantees that this glitch will give the player an expanded party. On the other hand, the contents of uninitialized SRAM is unpredictable: There is a good chance it will be 0xFF anyway, but it can also be something else. In particular, some emulators initialize the SRAM to 0x00, which means even if this glitch succeeded, it will not give the player an expanded party. 

I believe my emulator is initializing the content of RAM to 0x00 instead of the expected 0xFF.

Can you check if clearing the save file makes the glitch work? Or if you are already doing that.

**Comment by diabl0w** [comment]
> Your link has the following comment:
> 
> > Even if the player does not have an existing save file (e.g. on a fresh cart), it is still recommended to clear the save file anyway. Clearing the save file will set the SRAM to all 0xFF bytes, which guarantees that this glitch will give the player an expanded party. On the other hand, the contents of uninitialized SRAM is unpredictable: There is a good chance it will be 0xFF anyway, but it can also be something else. In particular, some emulators initialize the SRAM to 0x00, which means even if this glitch succeeded, it will not give the player an expanded party.
> 
> I believe my emulator is initializing the content of RAM to 0x00 instead of the expected 0xFF.
> 
> Can you check if clearing the save file makes the glitch work? Or if you are already doing that.

very good catch! i apologize for not noticing that. it does indeed work now, thank you

**Comment by Rodrigodd** [comment]
Fixed in https://github.com/Rodrigodd/gameroy/commit/3d3bb7ce0a017e2a00e89738891c72eb8038ef1f, thanks for the report!
